export type Idea = {
  id: string;
  index: string; // IDEA 01
  zh: string;
  en: string;
  def: string;
  refs: { label: string; num?: number; href?: string }[];
  accent?: "coral" | "magenta";
  motif: string;
  since: string;
};

export const ideas: Idea[] = [
  {
    id: "ruler",
    index: "IDEA 01",
    zh: "同一把尺子",
    en: "One Ruler, Two Directions",
    def: "向外，是 Eval——看见系统哪里偏了，把争论变成实验；向内，是内观——看见自己的判断哪里偏了，允许自己改错。真正的专业，不是永远判断正确，而是有一套更早发现错误、更快修正错误的机制。",
    refs: [{ label: "2026.08 信任进化（首发于本站）" }],
    accent: "coral",
    motif: "ruler",
    since: "2026",
  },
  {
    id: "aliveness",
    index: "IDEA 02",
    zh: "活人感",
    en: "The Feeling of Aliveness",
    def: "对话式智能体的第一体验门槛，不在参数和榜单里——在「像不像一个活人在跟你说话」：响应的节奏、打断的从容、情绪的呼应、记得你是谁。缺了它，再聪明也是玩具。",
    refs: [
      { label: "人人都是PM 2025", num: 8 },
      { label: "First Prompt SG", num: 9 },
      { label: "RTE 春夏巡游", num: 12 },
    ],
    motif: "wave",
    since: "2025",
  },
  {
    id: "hemispheres",
    index: "IDEA 03",
    zh: "被记住 · 被托付",
    en: "Remembered · Entrusted",
    def: "对话式智能体分化成两个物种：消费级让 AI 像人，终局是被记住；企业级让 AI 像系统，终局是被托付。物种分化，同源进化——底层是同一段 DNA、同一颗引擎。",
    refs: [
      { label: "AWS 中国峰会", num: 15 },
      { label: "INSPIRE 2026", num: 14 },
      { label: "RTE 春夏巡游", num: 12 },
    ],
    motif: "hemis",
    since: "2026",
  },
  {
    id: "bounds",
    index: "IDEA 04",
    zh: "模型上限 · 引擎下限",
    en: "Ceiling & Floor",
    def: "模型决定能力上限，引擎决定体验下限。所有人都在卷上限，但用户流失发生在下限——一次没接住的打断、一秒尴尬的沉默，比答错一道题伤得更重。",
    refs: [
      { label: "AWS 中国峰会", num: 15 },
      { label: "第三纪元", num: 6 },
    ],
    accent: "magenta",
    motif: "bounds",
    since: "2025",
  },
  {
    id: "vibe-sota",
    index: "IDEA 05",
    zh: "Vibe SOTA",
    en: "State of the Art, by Vibe",
    def: "语音智能体的 SOTA 不在 benchmark 榜单上，在 vibe 里。把「感觉对了」从一句玄学，变成可测量、可优化、可比较的体验基准——这是产品经理的手艺。",
    refs: [
      { label: "Voice Agent 闭门会", num: 10 },
      { label: "First Prompt SG", num: 9 },
    ],
    motif: "sota",
    since: "2026",
  },
  {
    id: "qoi",
    index: "IDEA 06",
    zh: "QoI · 第三纪元",
    en: "Quality of Interaction",
    def: "QoS 为传输设计，QoE 为人设计，QoI 为人模共演设计。实时体验的测量对象完成第三次迁移——从网络质量，到人的感受，到人与模型之间互动本身的质量。",
    refs: [
      { label: "RTE 春夏巡游", num: 12 },
      { label: "第三纪元", num: 6 },
      { label: "RTE 2024", num: 1 },
    ],
    motif: "qoi",
    since: "2024–2026",
  },
  {
    id: "four-steps",
    index: "IDEA 07",
    zh: "听得到 → 听得清 → 听得懂 → 听得心",
    en: "Four Stages of Listening",
    def: "对话体验的四阶段进化：从信号可达，到声音干净，到语义理解，到听出情绪与言外之意。每往上一阶，技术栈换一层，体验标准也换一把尺。",
    refs: [
      { label: "RTE 2024", num: 1 },
      { label: "人人都是PM 2024", num: 2 },
      { label: "第三纪元", num: 6 },
    ],
    motif: "steps",
    since: "2024",
  },
  {
    id: "tb",
    index: "IDEA 08",
    zh: "0.29 TB",
    en: "The Physics of Companionship",
    def: "一生说 10 亿个词，25% 值得记住，折合 3.2 年音频——0.29 TB，是一个人「生命上下文」的物理上限，也是机器人成为伙伴的记忆配额。21g 灵魂 × 0.29TB 记忆。",
    refs: [
      { label: "RTE 春夏巡游", num: 12 },
      { label: "AWS 中国峰会", num: 15 },
    ],
    motif: "tb",
    since: "2026",
  },
  {
    id: "eval-prd",
    index: "IDEA 09",
    zh: "评测即 PRD",
    en: "Eval Is the PRD",
    def: "AI 时代，产品经理的交付物变了：不再是功能清单，而是一把别人可以复用的尺子。写好一份评测，就是写好一份 PRD——先定义什么叫「对」，再让系统朝着它进化。",
    refs: [{ label: "公众号 NO.19 · 评测即 PRD", href: "/evalprd" }, { label: "体验基准", num: 8 }],
    motif: "evalprd",
    since: "2026",
  },
  {
    id: "turns-wrong",
    index: "IDEA 10",
    zh: "每一轮都对，整段却错",
    en: "Right Turns, Wrong Dialogue",
    def: "客服 Agent 的四种死法长得一模一样：逐轮看每句都无可挑剔，整段对话却背离了目标。评测的粒度必须从一轮升到一段——正确性，不能从局部求和。",
    refs: [{ label: "公众号 NO.18 · 四种死法", href: "/turns" }],
    motif: "turnsx",
    since: "2026",
  },
  {
    id: "not-the-model",
    index: "IDEA 11",
    zh: "胜负手不在模型",
    en: "Not the Model",
    def: "从 Sierra 的六件事，到 ElevenLabs 押注级联：赢下场景的从来不是模型本身，而是模型外面那一整套架构、流程与工程。上限人人共享，下限各凭本事。",
    refs: [{ label: "公众号 NO.12 · Sierra 六件事", href: "/csagent" }, { label: "NO.13 · 押注级联", href: "/arch" }],
    accent: "magenta",
    motif: "notmodel",
    since: "2026",
  },
  {
    id: "gold-standard",
    index: "IDEA 12",
    zh: "五维金标准",
    en: "The Five-Bar Gold Standard",
    def: "什么才算企业级智能体？五个维度一起达标才算——96.5% 的用户分辨不出 AI，只是入场券。金标准的意义，是把「可托付」从形容词变成可验收的清单。",
    refs: [{ label: "INSPIRE 2026", num: 14 }],
    motif: "gold5",
    since: "2026",
  },
  {
    id: "settle-72h",
    index: "IDEA 13",
    zh: "72 小时后才结算",
    en: "Settled After 72 Hours",
    def: "一通客服结束的那一刻，价值还没有发生：退款有没有再来、问题有没有复发，72 小时后才见分晓。把结算后置到效果出现之后，商业模式才终于和用户站在同一边。",
    refs: [{ label: "公众号 NO.23 · Outcome", href: "/outcome" }],
    motif: "settle72",
    since: "2026",
  },
  {
    id: "role-triad",
    index: "IDEA 14",
    zh: "角色三件套",
    en: "The Role Triad",
    def: "玩具与伙伴的分水岭不是智能，是角色：身份、关系、历史，三件套加一颗实时引擎。角色立住了，机器人才从被使用，走向被记住。",
    refs: [{ label: "RTE 春夏巡游", num: 12 }],
    motif: "triad",
    since: "2026",
  },
  {
    id: "agency-price",
    index: "IDEA 15",
    zh: "执行变便宜，人变贵",
    en: "Cheap Execution, Expensive Agency",
    def: "AI 把执行的价格打下来之后，人的价值迁移到 high agency：提出问题、下判断、担后果。比技能更稀缺的，是把自己也放上评测台的勇气。",
    refs: [{ label: "公众号 NO.27 · High Agency", href: "/highagency" }],
    motif: "agency",
    since: "2026",
  },
  {
    id: "compounding",
    index: "IDEA 16",
    zh: "Agent 恒动复利",
    en: "Perpetual Compounding",
    def: "Agent 和人最大的不同，是它不下班：任务在恒动中累积，理解在交接中沉淀。把 AI 当新同事带，复利从第一天开始滚。",
    refs: [{ label: "课程 · 带一个新同事上班", href: "/newcollege" }],
    motif: "compound",
    since: "2026",
  },
  {
    id: "time-fx",
    index: "IDEA 17",
    zh: "人间 3 天 · Claude 3 年",
    en: "The Time Exchange Rate",
    def: "人间只过了三天，模型像活过了三年。人与 AI 之间存在一条时间汇率——读懂它，才知道该在哪个时刻下注、按哪个刻度复盘。",
    refs: [{ label: "公众号 NO.10 · System Card 读后感", href: "/systemcard" }],
    motif: "timefx",
    since: "2026",
  },
  {
    id: "cowork-next",
    index: "IDEA 18",
    zh: "从被托付到共事",
    en: "From Entrusted to Co-working",
    def: "信任的下一跳：不再是单向的托付，而是双向的奔赴——人和智能体互相校准、互相担责。完整论证 2026.08 上台首发，此处先立一个刻度。",
    refs: [{ label: "2026.08 AI 产品经理大会 · 连载中" }],
    accent: "coral",
    motif: "cowork",
    since: "2026",
  },
];
